# CHAPTER-12_____________________________________________________File Handling.

***

## Key Points

* **Flie handling** is used to work with the files in python
* it can be initilized by useing **open()** Function  
```python
f=open("filename.txt","MODE")
```

| MODE |Syntex|                                 defination                              |
|------|------|-------------------------------------------------------------------------|
|Read  |  "r" |Default value. Opens a file for reading, error if the file does not exist|
|Append|  "a" |Opens a file for appending, creates the file if it does not exist        |
|Write |  "w" |Opens a file for writing, creates the file if it does not exist          |
|Create|  "x" |Creates the specified file, returns an error if the file exists          |



* **Note:** You should always close your files, in some cases, due to buffering, changes made to a file may not show until you close the file.
```python
f.close()
```

### Other general methods:
|  MODE   |       Syntex       |              defination                          |
|---------|--------------------|--------------------------------------------------|
|Tell     |f.tell()            |Tell the current posation of the curser           |
|Seek     |f.seek(**position**)|Set position of the curser into the giver posation|
|Readline |f.readline()        |read a full line                                  |
|Readlines|f.readlines()       |read all lines in the txt file                    |

### #demo.txt↴
<div class="alert alert-block alert-info">
Hello! this is a peragraph of "demo.txt" file.<br>  
This file is made for testing fector only.
</div>

## Making a File

## Read Files

In [14]:
f = open("demo.txt", "r") # opening the file in read mode

print(f.read()) # reading the file contant(ALL)

f.seek(0) # seting the posation of the curser in index 0

Hello! this is a peragraph of "demo.txt" file.
This file is made for testing fector only.


0

In [17]:
print("index befour reading",f.tell()) #current posation of the curser

print(f.read(15)) # read the starting 15 charactors

print("index after reading",f.tell())

index befour reading 0
Hello! this is 
index after reading 15


In [18]:
# reading another 15 char

f.read(15)

'a peragraph of '

### Reading lines

In [33]:
f.seek(0)
print(f.readline()) # reading first line
print(f.readline()) #reading second line

Hello! this is a peragraph of "demo.txt" file.

This file is made for testing fector only.


In [29]:
f.seek(0)
f.readlines() #reading lines in form of a array

['Hello! this is a peragraph of "demo.txt" file.\n',
 'This file is made for testing fector only.']

### reading useing loop

In [35]:
# read line by line
f.seek(0)
for x in f:
  print(x)

Hello! this is a peragraph of "demo.txt" file.

This file is made for testing fector only.


In [36]:
f.close()

## Write Files

In [7]:
f= open("demo.txt","w")  #Open file in write mode
f.read()  #as the file is open in write mode we can not read it.

UnsupportedOperation: not readable

#### before "write" function   
### #demo.txt↴
<div class="alert alert-block alert-info">
    Hello! this is a peragraph of "demo.txt" file.<br>
    This file is made for testing fector only.
</div>


In [10]:
f=open("demo.txt","w")
f.write("it will over write the pre return contant in the /'demo.txt/' file")

66

#### after "write" function  
### #demo.txt↴  
<div class="alert alert-block alert-info"> 
    it will over write the pre return contant in the /'demo.txt/' file
</div>

In [11]:
f.close()

## Append File
_it is used to append a text in the given file_

#### before "append" function  
### #demo.txt↴  
<div class="alert alert-block alert-info"> 
    it will over write the pre return contant in the /'demo.txt/' file
</div>

In [12]:
f = open("demo.txt","a")
f.write("this line of text will append after the prevous line/text")
f.close()

#### after "append" function  
### #demo.txt↴  
<div class="alert alert-block alert-info"> 
    it will over write the pre return contant in the /'demo.txt/' filethis line of text will append after the prevous line/text
</div>

## Delete Files

_**A file can not be delete useing methods of file handling**_

_**To delete a file from system**_
```python
import os
if os.path.exists("demofile.txt"):
  os.remove("demofile.txt")
else:
  print("The file does not exist")
```
_**↜ This can be used**_

## Question 1: Write a program in python to copy a file data from file "emp.txt" to the file "temp_emp.txt" useing file handling.  
emp:
<div class="alert alert-block alert-info">                  
Name:age:salary<br>
navneet:21:89000<br>
prakash:25:41000<br>
akshat:21:24000<br>
vicky:28:13000<br>
digvijay:19:20000<br>
</div>  

In [13]:
#creating the file emp.txt
make = open("emp.txt","x")  #x create file if it dosent exist alrady
make.close()

In [4]:
#adding data in emp.txt
name=["navneet","prakash","akshat","vicky","digvijay"]
salary=["89000","41000","24000","13000","20000"]
age=["21","25","21","28","19"]

add = open("emp.txt","a")
lines=[]
for i in range(5):
    lines.append(name[i]+":"+age[i]+":"+salary[i]+"\n")
add.writelines(lines)
add.close()


In [8]:
see = open ("emp.txt","r")
print(see.read())
see.close()

navneet:21:89000
prakash:25:41000
akshat:21:24000
vicky:28:13000
digvijay:19:20000
navneet:21:89000
prakash:25:41000
akshat:21:24000
vicky:28:13000
digvijay:19:20000



In [11]:
# creating and copying the data of "emp.txt" to the file "temp_emp.txt"

read = open("emp.txt","r")
copy = open("temp_emp.txt","a")

for data in read:
    copy.write(data+"\n")

read.close()
copy.close()

In [12]:
read = open("temp_emp.txt","r")
read.read()

'navneet:21:89000\n\nprakash:25:41000\n\nakshat:21:24000\n\nvicky:28:13000\n\ndigvijay:19:20000\n\nnavneet:21:89000\n\nprakash:25:41000\n\nakshat:21:24000\n\nvicky:28:13000\n\ndigvijay:19:20000\n\n'

In [13]:
read.close()

## Question 2: Write a program in python to maintain the records of employees in a text file.

<div class="alert alert-block alert-success"> 
    <h3 style="color:black;">NOTE:-</h3> <span style="color:blue">enumeate()</span><span> function</span><br>
    syntex:- enumerate(iterable, start=0)
</div>

|name|age|joining-date|Department|phone-number|email|employ-id|
|----|---|------------|----------|------------|-----|---------|
|Navneet|21|01/01/2023|data analyst|9368685547 ,9997456123|updeshroy816@gmail.com|ESV156752 , VAD456752|
|Akshat |19|21/05/2022|manager     |654685547  ,8409746123|popliakshat@gmail.com |HGDFE544  , YTFV36465|

In [1]:
def display():
    try:
        r = open("emp_records.txt","r")
        print(r.read())
        r.close()
    except:
        print("invalid!")
        print("file not found")

In [2]:
def make():
    print("please enter the following perameters:")
    name=input("name :")
    age = input("age :")
    joining_date = input("joining-date :")
    Department = input("Department :")
    phone_number = input("phone-number :")
    email = input("email :")
    employ_id = input("employ_id :")
    mk = open("emp_records.txt","a")
    mk.write(name+":"+age+":"+joining_date+":"+Department+":"+phone_number+":"+email+":"+employ_id+"\n")
    mk.close()

In [3]:
def search():
    search = input("name of the person you want to search:")
    r = open("emp_records.txt","r")
    lines=r.readlines()
    r.close()
    c=0
    for line in lines:
        if search in line:
            c=c+1
            print(line) 
    if c==0:
        print("data not found")

In [4]:
def delete():
    s =input("whose data you want to delete:-")
    d = open("emp_records.txt","r") # read write mode
    lines=d.readlines()
    d.close()
    c=0
    for line in lines:
        if s in line:
            c=c+1
            lines.remove(line)
            d = open("emp_records.txt","w")
            d.writelines(lines)
            print("record remover successfully")
            d.close()
    if c==0:
        print("data not found")

In [5]:
def update():
    upd=input("whome you want to update:")
    f = open("emp_records.txt","r")
    lines=f.readlines()
    f.close()
    c=0
    for line in lines:
        if upd in line:
            c=c+1
            lines.remove(line)
            d = open("emp_records.txt","w")
            d.writelines(lines)
            d.close()
            make()
    if c==0:
        print("success fully updated")
            
    

# CHAPTER-13_____________________________________________________DBMS Python.

## DBMS:
* _**Database Management Systems (DBMS)** are software systems used to store, retrieve, and run queries on data._
* _A **DBMS** serves as an interface between an end-user and a database_
* _allowing users to **create, read, update, and delete data** in the database._  
## Database:
_**A database** is an organized collection of structured information, or data, typically stored electronically in a computer system._

![database type](https://static.javatpoint.com/dbms/images/types-of-databases.png)

_To connect python to database we use **XAMPP server**_  
**XAMPP server**_ it provides a graphical interface for SQL (phpMyAdmin)  
* XAMPP making it easy to maintain data in a relational databas_

![XAMPP logo](https://www.enovision.net/storage/legacy/image172.png)

***

## Working with XAMPP in python?

<div style="display:flex;">
    <div >
        <h2>STEP-1</h2>
      <img style="height:200px;" src="https://www.ionos.com/digitalguide/fileadmin/_processed_/4/e/csm_EN_XAMPP_Control_Panel_1_f188c94826.webp">  
    </div>
    <div>
        <h2>STEP-2</h2>
      <img style="height:200px;" src="https://www.researchgate.net/profile/Ching-Yu-Huang/publication/333268979/figure/fig1/AS:761349944643584@1558531380038/The-main-graphic-user-interface-of-XAMPP.ppm">  
    </div>
    <div>
        <h2>STEP-3</h2>
      <img style="height:200px;" src="https://www.wa4e.com/images/xampp-win-01-panel.png">  
    </div>
</div>    

_Now both the **apache** and **MySQL** servers are running_  
_**Apache is a web server software** that is responsible for accepting HTTP requests from visitors and sending them back the requested information in the form of web pages._

<div class="alert alert-block alert-warning">
<p>NOTE:-Search"http://localhost/phpmyadmin/" to open localhost MYSQL</p>
</div>

## Connecting python with MYSQL

In [10]:
import pymysql  #importing pymysql to connect through DBMS

db = pymysql.connect(host='localhost',
                             user='root',
                             password='',
                             database='friends',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
        
                                  #hostname #username #password #databasename
        
cursor = db.cursor()
sql = """SELECT * FROM teacher"""
cursor.execute(sql)

1

**Proper way to write mysql quarry in python**

In [11]:
sql = """INSERT INTO teacher(FIRST_NAME,LAST_NAME, AGE, SEX, INCOME)VALUES ('Amit', 'Sharma', 22, 'M', 2000)"""
try:
    cursor.execute(sql)
    db.commit()  # parmanently saved.
except: # this block will execute if there is any exception
    db.rollback()  # do not save transactions.(do not execute sql)

In [12]:
sql = "UPDATE teacher SET AGE = AGE + 1 WHERE SEX = '%c'" % ('M')
try:
    cursor.execute(sql)
    db.commit()
except:    
    db.rollback()

|method|TYPE|Queries|
|------|----|-------|
|Create|database|CREATE DATABASE **database name**;|
|      |table   |CREATE TABLE **table name**<br>(<br>**id** INT AUTO_INCREMENT,<br>**first_name** VARCHAR(100),<br>**last_name** VARCHAR(100),<br>**email** VARCHAR(50),<br>**password** VARCHAR(20),<br>**location** VARCHAR(100),<br>**dept** VARCHAR(100),<br>**is_admin** TINYINT(1),<br>**register_date** DATETIME,<br>PRIMARY KEY(id)<br>);

|method|TYPE|Queries|
|------|----|-------|
|Delete|database|DROP DATABASE **database name**;|
|      |table   |DROP TABLE **tablename**;|

|method|TYPE|Queries|
|------|----|-------|
|Insert|Single row|INSERT INTO users (first_name, last_name, email, password, location, dept, is_admin, register_date) values ('Brad', 'Traversy', 'brad@gmail.com', '123456','Massachusetts', 'development', 1, now());|
|      |multiple row|INSERT INTO users (first_name, last_name, email, password, location, dept,  is_admin, register_date) values ('Fred', 'Smith', 'fred@gmail.com', '123456', 'New York', 'design', 0, now()), ('Sara', 'Watson', 'sara@gmail.com', '123456', 'New York', 'design', 0, now()),<br>('Will', 'Jackson', 'will@yahoo.com', '123456', 'Rhode Island', 'development', 1, now()),('Paula', 'Johnson', 'paula@yahoo.com', '123456', 'Massachusetts', 'sales', 0, now()),('Tom', 'Spears', 'tom@yahoo.com', '123456', 'Massachusetts', 'sales', 0, now());


|method|TYPE|Queries|
|------|----|-------|
|show  |table|SHOW TABLES;|
|exit  |database|exit;|
|Select|Database|USE **use database**;|
|      |table   |SELECT * FROM **users**;<br>SELECT **first_name, last_name** FROM **users**;|
|      |table where|SELECT * FROM users WHERE location='Massachusetts';<br>SELECT * FROM **users** WHERE **location**=**'Massachusetts**' AND **dept**='**sales**';<br>SELECT * FROM **users** WHERE is_admin = **1**;<br>SELECT * FROM **users** WHERE is_admin > **0**;)
|      |table order|SELECT * FROM **users** ORDER BY **last_name** ASC;<br>SELECT * FROM **users** ORDER BY **last_name** DESC;|
|      |table like|SELECT * FROM **users** WHERE **dept** LIKE '**d%**';<br>SELECT * FROM **users** WHERE **dept** LIKE '**dev%**';<br>SELECT * FROM **users** WHERE **dept** LIKE '**%t**';<br>SELECT * FROM **users** WHERE **dept** LIKE '**%e%**';|
|Add New Column|table|ALTER TABLE **users** ADD **age VARCHAR(3)**;|
|Modify Column|table|ALTER TABLE **users** MODIFY COLUMN **age INT(3)**;|
|Update Row|table|UPDATE **users** SET **email** = '**freddy@gmail.com**' WHERE **id = 2**;|
|Select Distinct Rows|table|SELECT DISTINCT location FROM users;|
|Between (Select Range)|table|SELECT * FROM users WHERE age BETWEEN 20 AND 25;|
|group by|table|SELECT **age**, COUNT(**age**) FROM **users** GROUP BY **age**;<br>SELECT **age**, COUNT(**age**) FROM **users** WHERE **age > 20** GROUP BY **age**;<br>SELECT **age**, COUNT(**age**) FROM **users** GROUP BY **age** HAVING count(**age**) >=**2**;|

# CHAPTER-14_____________________________________________________In-Depth Python Features.

In [ ]:
# lambda, with statement,split, try/except, x for x in range(),

1. import **time**
1. import **random**
1. import **turtle**
1. import **os**
1. import **tkinter**
1. import **requests**
1. import **csv**

# CHAPTER-15_____________________________________________________Basic Statistics.

# CHAPTER-16_____________________________________________________Statistical graphs.

# CHAPTER-17_____________________________________________________Python Numpy.

## **Numpy** _is a Python library used for working with 1D,2D,3D array_
* **Array** _is same like the list used to store collection_
* **Array index** _is same as python index_

## CREATING numpy arrays 

<div class="alert alert-block alert-warning">                  
<center><h3><b>BASIC</b></h3></center>
</div>  

In [3]:
# 1d array
import numpy as np
arr_1d = np.array([1,2,3,4,5,6,7,8,9])
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 2d array
import numpy as np
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
# 3d array
import numpy as np
arr_3d = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
arr_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

<div class="alert alert-block alert-warning">                  
<center><h3><b>useing:-"arange"</b></h3></center>
</div>  

**arange:**  
it is used to make a np array by defining a range for it 
* it is used to make only 1-D array
* **Syntax:-**
* * np.arange(start,stop-1,step)

In [5]:
# arange(start,stop)
import numpy as np
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [7]:
# arange(start,stop,step)
import numpy as np
arr = np.arange(0,21,4)
arr

array([ 0,  4,  8, 12, 16, 20])

<div class="alert alert-block alert-warning">                  
<center><h3><b>useing:-"random"</b></h3></center>
</div>  

**random module**
|syntax|--USE--|
|------|-------|
|np.random.randint(start,stop,size)|it give the random array between the range of the size|
|np.random.random(size)|it give the random number between 0 to 1 of the given size|

In [14]:
# randint 1d
import numpy as np
arr=np.random.randint(5,19,4)
arr

array([14, 17, 10, 18])

In [15]:
# randint 2d
import numpy as np
arr=np.random.randint(5,19,(2,4))
arr

array([[13,  7, 11, 13],
       [12, 10, 15, 12]])

In [16]:
# randint 3d
import numpy as np
arr=np.random.randint(5,19,(2,4,6))
arr

array([[[17, 10, 15, 14, 13, 13],
        [ 7, 18,  9,  5, 13, 16],
        [ 7, 13,  9,  6, 18, 15],
        [ 9,  6, 17, 18,  6,  9]],

       [[16, 15, 14, 16,  8, 12],
        [ 9, 16,  8, 11, 15, 17],
        [18, 15, 13, 18, 11,  7],
        [ 6,  8,  9, 14,  8, 10]]])

***

In [17]:
# random 1d
import numpy as np
arr = np.random.random(4)
arr

array([0.81109525, 0.54825063, 0.14487131, 0.82824787])

In [18]:
# random 2d
import numpy as np
arr = np.random.random((2,4))
arr

array([[0.47740099, 0.14864884, 0.56872024, 0.27375748],
       [0.58237376, 0.90367401, 0.89409546, 0.61717411]])

In [19]:
# random 3d
import numpy as np
arr = np.random.random((2,4,6))
arr

array([[[0.07743122, 0.3776119 , 0.8698661 , 0.80444607, 0.47839819,
         0.56187775],
        [0.82326614, 0.90144645, 0.79535725, 0.76746851, 0.94289312,
         0.02940013],
        [0.65142055, 0.08986743, 0.32540603, 0.0723826 , 0.93595505,
         0.61366391],
        [0.18158003, 0.94205011, 0.42202287, 0.83051316, 0.84568007,
         0.36105203]],

       [[0.54619484, 0.69296648, 0.71950955, 0.99946001, 0.80920447,
         0.61804115],
        [0.03699399, 0.24268561, 0.63808847, 0.34505597, 0.67920782,
         0.51353867],
        [0.29096087, 0.25756638, 0.64428673, 0.8238065 , 0.25421889,
         0.57559579],
        [0.6373608 , 0.27201972, 0.24884959, 0.99618286, 0.18583868,
         0.98669255]]])

<div class="alert alert-block alert-warning">                  
<center><h3><b>-- OTHERS --</b></h3></center>
</div>  

|syntax|USE|
|------|---|
|np.zeros((3,4))|create a array of zeros of size 3\*4|
|np.ones((2,3,4),dtype=np.int16)|create a array of ones of size 2\*3\*4|
|np.full((2,2),7)|create a constant array of 7(in this case) of size 2\*2|
| np.eye(2)|create a 2\*2 identity matrix|
| np.empty((3,2))|create aempty matrix with garbage value ofsize 3\*2|

In [23]:
import numpy as np
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
import numpy as np
arr=np.ones((2,3,4),dtype=np.int16)
arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
import numpy as np
arr=np.full((2,2),7)
arr

array([[7, 7],
       [7, 7]])

In [2]:
import numpy as np
arr=np.eye(10)
arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
import numpy as np
arr=np.empty((3,2))
arr

array([[7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304]])

## Mathematics

<div class="alert alert-block alert-warning">                  
<center><h3><b>Arithmetic Operations</b></h3></center>
</div>  

|Syntax|USE|
|------|---|
|**\+**|Addition|
|**\-**|Subtraction|
|**\***|multiplaction|
|**\/**|division|
|np.sqrt(b)|Square root|
|np.sin(a)|Print sines of an array|
|np.cos(b)|Elementwise cosine|
|np,tan(b)|value of tan|
|np.log(a)|Elementwise natural logarithm|
|np.log2(a)|Elementwise natural logarithm with base 2|

In [30]:
a=np.arange(1,7)
b=np.arange(4,10)
print(a)
print(b)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [35]:
c=a+b
c

array([ 5,  7,  9, 11, 13, 15])

In [36]:
c=a-b
c

array([-3, -3, -3, -3, -3, -3])

In [37]:
c=a*b
c

array([ 4, 10, 18, 28, 40, 54])

In [38]:
c=a/b
c

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
       0.66666667])

In [39]:
c=np.sqrt(a)
c

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [40]:
c=np.sin(a)
c

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [41]:
c=np.cos(a)
c

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

In [42]:
c=np.tan(a)
c

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619])

In [43]:
c=np.log(a)
c

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [44]:
c=np.log2(a)
c

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 ])

<div class="alert alert-block alert-warning">                  
<center><h3><b>Aggregate Functions</b></h3></center>
</div>  

|syntax|USE|
|------|---|
|a.sum()|Array-wise sum
|a.min()|Array-wise minimum value
|b.max(axis=0)|Maximum value of an array row
|b.cumsum(axis=1)|Cumulative sum of the elements
|a.mean()|Mean
|np.median()|Median
|np.corrcoef()|Correlation coefficient
|np.std()|Standard deviation
|np.var()|variance|

In [51]:
a=np.random.randint(0,11,(2,5))
a

array([[4, 6, 3, 7, 3],
       [3, 6, 6, 0, 9]])

In [52]:
c=a.sum()
c

47

In [53]:
c=a.min()
c

0

In [58]:
#max value of all the rows
c=a.max(axis=0)
c

array([4, 6, 6, 7, 9])

In [62]:
# sum of numbers as we go up
c=a.cumsum(axis=1)
c

array([[ 4, 10, 13, 20, 23],
       [ 3,  9, 15, 15, 24]])

In [64]:
c=a.mean()
c

4.7

In [66]:
c=np.median(a)
c

5.0

In [69]:
c=np.corrcoef(a)
c

array([[ 1.       , -0.7000666],
       [-0.7000666,  1.       ]])

In [70]:
c=np.std(a)
c

2.4515301344262523

In [76]:
c=np.var(a)
c

6.01

## Array Manipulation

<div class="alert alert-block alert-warning">                  
<center><h3><b>Inspecting array</b></h3></center>
</div>

|syntax|USE|
|------|---|
|a.shape|tell the shaps of array|
|len(a)|tell length of the array|
|a.ndim|tell dimnation of the array|
|a.size|tell size of the array|
|a.dtype|tell datatypes of array elements|
|a.dtype.name|tell name of datatype of array elements| 
|a.astype(int)|convert data type of the aray element|

In [78]:
import numpy as np
a=np.random.randint(1,21,(3,5))
a

array([[ 4,  6, 20,  7, 20],
       [14, 17, 15, 15,  6],
       [ 7,  7, 20, 12,  9]])

In [80]:
c=a.shape
c

(3, 5)

In [81]:
c=len(a)
c

3

In [82]:
c=a.ndim
c

2

In [84]:
c=a.size
c

15

In [85]:
c=a.dtype
c

dtype('int32')

In [86]:
c=a.dtype.name
c

'int32'

In [87]:
c=a.astype(str)
c

array([['4', '6', '20', '7', '20'],
       ['14', '17', '15', '15', '6'],
       ['7', '7', '20', '12', '9']], dtype='<U11')

<div class="alert alert-block alert-warning">                  
<center><h3><b>Subsetting,Slicing, Indexing</b></h3></center>
</div> 

**slicing**

![array index](https://media.geeksforgeeks.org/wp-content/uploads/Numpy1.jpg)

***

In [88]:
a=np.arange(0,36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [90]:
a=a.reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

**index**  
<img src="https://www.oreilly.com/api/v2/epubs/9781449323592/files/httpatomoreillycomsourceoreillyimages2172112.png" style="width:300px">

In [92]:
print(a[0][1])
print(a[0][2])
print(a[0][3])
print(a[1][0])

1
2
3
6


**SUBSET**  
a[row,column,width]

In [94]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [96]:
sub=a[2:4]
sub

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [98]:
sub=a[2:4,1:6]
sub

array([[13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23]])

In [101]:
sub=a[2:5,2:5]
sub

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

<div class="alert alert-block alert-success">                  
<p><b>note:</b>if we change any value in subset it will cause change in his parent array also</p>
<p>to prevent that we can use <b>np.copy(a)</b></p>
</div>    

In [102]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [103]:
sub=a[2:5,2:5]
sub

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [105]:
sub[0][0]=1000
sub

array([[1000,   15,   16],
       [  20,   21,   22],
       [  26,   27,   28]])

In [106]:
a

array([[   0,    1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,   11],
       [  12,   13, 1000,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35]])

In [107]:
sub=np.copy(a[2:5,2:5])
sub

array([[1000,   15,   16],
       [  20,   21,   22],
       [  26,   27,   28]])

In [108]:
sub[0][0]=68783268
sub

array([[68783268,       15,       16],
       [      20,       21,       22],
       [      26,       27,       28]])

In [109]:
# no change
a

array([[   0,    1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,   11],
       [  12,   13, 1000,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35]])

<div class="alert alert-block alert-warning">                  
<center><h3><b>Adding / Removing elements</b></h3></center>
</div> 

|SYNTAX|USE|
|------|---|
|a.reshape((2,5))|Return a new array with shape(2,5)|
|np.append(a,temp)|Append items to an array|
|np.insert(a,1,5)|Insert items in an array|
|np.delete(a,[1])|Delete items from an array|

In [115]:
import numpy as np
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
b=a.reshape((2,5))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [117]:
temp=np.arange(10,16)
print("a =",a)
print("temp =",temp)
c=np.append(a,temp)
print("c =",c)

a = [0 1 2 3 4 5 6 7 8 9]
temp = [10 11 12 13 14 15]
c = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [119]:
c=np.insert(c,0,99)
c

array([99,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [120]:
c=np.delete(c,[0])
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

<div class="alert alert-block alert-warning">                  
<center><h3><b>Combining / splitting arrays</b></h3></center>
</div> 

In [131]:
a=np.array([[1,2,3,4,5],[11,22,33,44,55]])
b=np.array([[6,7,8,9,10],[66,77,88,99,110]])
print(a)
print(b)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
[[  6   7   8   9  10]
 [ 66  77  88  99 110]]


In [133]:
np.concatenate((a,b),axis=0)

array([[  1,   2,   3,   4,   5],
       [ 11,  22,  33,  44,  55],
       [  6,   7,   8,   9,  10],
       [ 66,  77,  88,  99, 110]])

In [134]:
np.concatenate((a,b),axis=1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110]])

In [140]:
c=np.vstack((a,b))
c

array([[  1,   2,   3,   4,   5],
       [ 11,  22,  33,  44,  55],
       [  6,   7,   8,   9,  10],
       [ 66,  77,  88,  99, 110]])

In [141]:
c2=np.hstack((a,b))
c2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110]])

In [148]:
np.hsplit(c2,5)

[array([[ 1,  2],
        [11, 22]]),
 array([[ 3,  4],
        [33, 44]]),
 array([[ 5,  6],
        [55, 66]]),
 array([[ 7,  8],
        [77, 88]]),
 array([[  9,  10],
        [ 99, 110]])]

In [150]:
np.vsplit(c,4)

[array([[1, 2, 3, 4, 5]]),
 array([[11, 22, 33, 44, 55]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[ 66,  77,  88,  99, 110]])]

In [154]:
for data in np.hsplit(c2,5):
    print(np.hsplit(data,2))

[array([[ 1],
       [11]]), array([[ 2],
       [22]])]
[array([[ 3],
       [33]]), array([[ 4],
       [44]])]
[array([[ 5],
       [55]]), array([[ 6],
       [66]])]
[array([[ 7],
       [77]]), array([[ 8],
       [88]])]
[array([[ 9],
       [99]]), array([[ 10],
       [110]])]


<div class="alert alert-block alert-warning">                  
<center><h3><b>OTHERS</b></h3></center>
</div> 

|SYNTAX|USE|
|------|---|
|a.reshape()|it reshape the array|
|np.transpose(a)| swip rows and columns with each other|
|np.linspace(0,2,9)|Create an array of evenly spaced values(number of samples)| 
|a.sort()|Sort an array|
|c.sort(axis=0)|Sort the elements of an array's axis|

In [167]:
import numpy as np
a=np.random.randint(1,45,15)
a

array([ 1, 40, 25, 16,  7, 15, 10, 11, 26, 25, 14, 22, 33, 42, 27])

In [168]:
a=a.reshape((3,5))
a

array([[ 1, 40, 25, 16,  7],
       [15, 10, 11, 26, 25],
       [14, 22, 33, 42, 27]])

In [169]:
a=np.transpose(a)
a

array([[ 1, 15, 14],
       [40, 10, 22],
       [25, 11, 33],
       [16, 26, 42],
       [ 7, 25, 27]])

In [170]:
np.sort(a,axis=0)

array([[ 1, 10, 14],
       [ 7, 11, 22],
       [16, 15, 27],
       [25, 25, 33],
       [40, 26, 42]])

In [174]:
np.linspace(0,4,9)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

# CHAPTER-18_____________________________________________________Python pandas.

# CHAPTER-19_____________________________________________________Statistical covariance.