# CHAPTER-12_____________________________________________________File Handling.

***

## Key Points

* **Flie handling** is used to work with the files in python
* it can be initilized by useing **open()** Function  
```python
f=open("filename.txt","MODE")
```

| MODE |Syntex|                                 defination                              |
|------|------|-------------------------------------------------------------------------|
|Read  |  "r" |Default value. Opens a file for reading, error if the file does not exist|
|Append|  "a" |Opens a file for appending, creates the file if it does not exist        |
|Write |  "w" |Opens a file for writing, creates the file if it does not exist          |
|Create|  "x" |Creates the specified file, returns an error if the file exists          |



* **Note:** You should always close your files, in some cases, due to buffering, changes made to a file may not show until you close the file.
```python
f.close()
```

### Other general methods:
|  MODE   |       Syntex       |              defination                          |
|---------|--------------------|--------------------------------------------------|
|Tell     |f.tell()            |Tell the current posation of the curser           |
|Seek     |f.seek(**position**)|Set position of the curser into the giver posation|
|Readline |f.readline()        |read a full line                                  |
|Readlines|f.readlines()       |read all lines in the txt file                    |

### #demo.txt↴
<div class="alert alert-block alert-info">
Hello! this is a peragraph of "demo.txt" file.<br>  
This file is made for testing fector only.
</div>

## Making a File

## Read Files

In [14]:
f = open("demo.txt", "r") # opening the file in read mode

print(f.read()) # reading the file contant(ALL)

f.seek(0) # seting the posation of the curser in index 0

Hello! this is a peragraph of "demo.txt" file.
This file is made for testing fector only.


0

In [17]:
print("index befour reading",f.tell()) #current posation of the curser

print(f.read(15)) # read the starting 15 charactors

print("index after reading",f.tell())

index befour reading 0
Hello! this is 
index after reading 15


In [18]:
# reading another 15 char

f.read(15)

'a peragraph of '

### Reading lines

In [33]:
f.seek(0)
print(f.readline()) # reading first line
print(f.readline()) #reading second line

Hello! this is a peragraph of "demo.txt" file.

This file is made for testing fector only.


In [29]:
f.seek(0)
f.readlines() #reading lines in form of a array

['Hello! this is a peragraph of "demo.txt" file.\n',
 'This file is made for testing fector only.']

### reading useing loop

In [35]:
# read line by line
f.seek(0)
for x in f:
  print(x)

Hello! this is a peragraph of "demo.txt" file.

This file is made for testing fector only.


In [36]:
f.close()

## Write Files

In [7]:
f= open("demo.txt","w")  #Open file in write mode
f.read()  #as the file is open in write mode we can not read it.

UnsupportedOperation: not readable

#### before "write" function   
### #demo.txt↴
<div class="alert alert-block alert-info">
    Hello! this is a peragraph of "demo.txt" file.<br>
    This file is made for testing fector only.
</div>


In [10]:
f=open("demo.txt","w")
f.write("it will over write the pre return contant in the /'demo.txt/' file")

66

#### after "write" function  
### #demo.txt↴  
<div class="alert alert-block alert-info"> 
    it will over write the pre return contant in the /'demo.txt/' file
</div>

In [11]:
f.close()

## Append File
_it is used to append a text in the given file_

#### before "append" function  
### #demo.txt↴  
<div class="alert alert-block alert-info"> 
    it will over write the pre return contant in the /'demo.txt/' file
</div>

In [12]:
f = open("demo.txt","a")
f.write("this line of text will append after the prevous line/text")
f.close()

#### after "append" function  
### #demo.txt↴  
<div class="alert alert-block alert-info"> 
    it will over write the pre return contant in the /'demo.txt/' filethis line of text will append after the prevous line/text
</div>

## Delete Files

_**A file can not be delete useing methods of file handling**_

_**To delete a file from system**_
```python
import os
if os.path.exists("demofile.txt"):
  os.remove("demofile.txt")
else:
  print("The file does not exist")
```
_**↜ This can be used**_

## Question 1: Write a program in python to copy a file data from file "emp.txt" to the file "temp_emp.txt" useing file handling.  
emp:
<div class="alert alert-block alert-info">                  
Name:age:salary<br>
navneet:21:89000<br>
prakash:25:41000<br>
akshat:21:24000<br>
vicky:28:13000<br>
digvijay:19:20000<br>
</div>  

In [13]:
#creating the file emp.txt
make = open("emp.txt","x")  #x create file if it dosent exist alrady
make.close()

In [4]:
#adding data in emp.txt
name=["navneet","prakash","akshat","vicky","digvijay"]
salary=["89000","41000","24000","13000","20000"]
age=["21","25","21","28","19"]

add = open("emp.txt","a")
lines=[]
for i in range(5):
    lines.append(name[i]+":"+age[i]+":"+salary[i]+"\n")
add.writelines(lines)
add.close()


In [8]:
see = open ("emp.txt","r")
print(see.read())
see.close()

navneet:21:89000
prakash:25:41000
akshat:21:24000
vicky:28:13000
digvijay:19:20000
navneet:21:89000
prakash:25:41000
akshat:21:24000
vicky:28:13000
digvijay:19:20000



In [11]:
# creating and copying the data of "emp.txt" to the file "temp_emp.txt"

read = open("emp.txt","r")
copy = open("temp_emp.txt","a")

for data in read:
    copy.write(data+"\n")

read.close()
copy.close()

In [12]:
read = open("temp_emp.txt","r")
read.read()

'navneet:21:89000\n\nprakash:25:41000\n\nakshat:21:24000\n\nvicky:28:13000\n\ndigvijay:19:20000\n\nnavneet:21:89000\n\nprakash:25:41000\n\nakshat:21:24000\n\nvicky:28:13000\n\ndigvijay:19:20000\n\n'

In [13]:
read.close()

## Question 2: Write a program in python to maintain the records of employees in a text file.

<div class="alert alert-block alert-success"> 
    <h3 style="color:black;">NOTE:-</h3> <span style="color:blue">enumeate()</span><span> function</span><br>
    syntex:- enumerate(iterable, start=0)
</div>

|name|age|joining-date|Department|phone-number|email|employ-id|
|----|---|------------|----------|------------|-----|---------|
|Navneet|21|01/01/2023|data analyst|9368685547 ,9997456123|updeshroy816@gmail.com|ESV156752 , VAD456752|
|Akshat |19|21/05/2022|manager     |654685547  ,8409746123|popliakshat@gmail.com |HGDFE544  , YTFV36465|

In [1]:
def display():
    try:
        r = open("emp_records.txt","r")
        print(r.read())
        r.close()
    except:
        print("invalid!")
        print("file not found")

In [2]:
def make():
    print("please enter the following perameters:")
    name=input("name :")
    age = input("age :")
    joining_date = input("joining-date :")
    Department = input("Department :")
    phone_number = input("phone-number :")
    email = input("email :")
    employ_id = input("employ_id :")
    mk = open("emp_records.txt","a")
    mk.write(name+":"+age+":"+joining_date+":"+Department+":"+phone_number+":"+email+":"+employ_id+"\n")
    mk.close()

In [3]:
def search():
    search = input("name of the person you want to search:")
    r = open("emp_records.txt","r")
    lines=r.readlines()
    r.close()
    c=0
    for line in lines:
        if search in line:
            c=c+1
            print(line) 
    if c==0:
        print("data not found")

In [4]:
def delete():
    s =input("whose data you want to delete:-")
    d = open("emp_records.txt","r") # read write mode
    lines=d.readlines()
    d.close()
    c=0
    for line in lines:
        if s in line:
            c=c+1
            lines.remove(line)
            d = open("emp_records.txt","w")
            d.writelines(lines)
            print("record remover successfully")
            d.close()
    if c==0:
        print("data not found")

In [5]:
def update():
    upd=input("whome you want to update:")
    f = open("emp_records.txt","r")
    lines=f.readlines()
    f.close()
    c=0
    for line in lines:
        if upd in line:
            c=c+1
            lines.remove(line)
            d = open("emp_records.txt","w")
            d.writelines(lines)
            d.close()
            make()
    if c==0:
        print("success fully updated")
            
    

# CHAPTER-13_____________________________________________________DBMS Python.

## DBMS:
* _**Database Management Systems (DBMS)** are software systems used to store, retrieve, and run queries on data._
* _A **DBMS** serves as an interface between an end-user and a database_
* _allowing users to **create, read, update, and delete data** in the database._  
## Database:
_**A database** is an organized collection of structured information, or data, typically stored electronically in a computer system._

![database type](https://static.javatpoint.com/dbms/images/types-of-databases.png)

_To connect python to database we use **XAMPP server**_  
**XAMPP server**_ it provides a graphical interface for SQL (phpMyAdmin)  
* XAMPP making it easy to maintain data in a relational databas_

![XAMPP logo](https://www.enovision.net/storage/legacy/image172.png)

***

## Working with XAMPP in python?

<div style="display:flex;">
    <div >
        <h2>STEP-1</h2>
      <img style="height:200px;" src="https://www.ionos.com/digitalguide/fileadmin/_processed_/4/e/csm_EN_XAMPP_Control_Panel_1_f188c94826.webp">  
    </div>
    <div>
        <h2>STEP-2</h2>
      <img style="height:200px;" src="https://www.researchgate.net/profile/Ching-Yu-Huang/publication/333268979/figure/fig1/AS:761349944643584@1558531380038/The-main-graphic-user-interface-of-XAMPP.ppm">  
    </div>
    <div>
        <h2>STEP-3</h2>
      <img style="height:200px;" src="https://www.wa4e.com/images/xampp-win-01-panel.png">  
    </div>
</div>    

_Now both the **apache** and **MySQL** servers are running_  
_**Apache is a web server software** that is responsible for accepting HTTP requests from visitors and sending them back the requested information in the form of web pages._

<div class="alert alert-block alert-warning">
<p>NOTE:-Search"http://localhost/phpmyadmin/" to open localhost MYSQL</p>
</div>

## Connecting python with MYSQL

In [10]:
import pymysql  #importing pymysql to connect through DBMS

db = pymysql.connect(host='localhost',
                             user='root',
                             password='',
                             database='friends',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
        
                                  #hostname #username #password #databasename
        
cursor = db.cursor()
sql = """SELECT * FROM teacher"""
cursor.execute(sql)

1

**Proper way to write mysql quarry in python**

In [11]:
sql = """INSERT INTO teacher(FIRST_NAME,LAST_NAME, AGE, SEX, INCOME)VALUES ('Amit', 'Sharma', 22, 'M', 2000)"""
try:
    cursor.execute(sql)
    db.commit()  # parmanently saved.
except: # this block will execute if there is any exception
    db.rollback()  # do not save transactions.(do not execute sql)

In [12]:
sql = "UPDATE teacher SET AGE = AGE + 1 WHERE SEX = '%c'" % ('M')
try:
    cursor.execute(sql)
    db.commit()
except:    
    db.rollback()

|method|TYPE|Queries|
|------|----|-------|
|Create|database|CREATE DATABASE **database name**;|
|      |table   |CREATE TABLE **table name**<br>(<br>**id** INT AUTO_INCREMENT,<br>**first_name** VARCHAR(100),<br>**last_name** VARCHAR(100),<br>**email** VARCHAR(50),<br>**password** VARCHAR(20),<br>**location** VARCHAR(100),<br>**dept** VARCHAR(100),<br>**is_admin** TINYINT(1),<br>**register_date** DATETIME,<br>PRIMARY KEY(id)<br>);

|method|TYPE|Queries|
|------|----|-------|
|Delete|database|DROP DATABASE **database name**;|
|      |table   |DROP TABLE **tablename**;|

|method|TYPE|Queries|
|------|----|-------|
|Insert|Single row|INSERT INTO users (first_name, last_name, email, password, location, dept, is_admin, register_date) values ('Brad', 'Traversy', 'brad@gmail.com', '123456','Massachusetts', 'development', 1, now());|
|      |multiple row|INSERT INTO users (first_name, last_name, email, password, location, dept,  is_admin, register_date) values ('Fred', 'Smith', 'fred@gmail.com', '123456', 'New York', 'design', 0, now()), ('Sara', 'Watson', 'sara@gmail.com', '123456', 'New York', 'design', 0, now()),<br>('Will', 'Jackson', 'will@yahoo.com', '123456', 'Rhode Island', 'development', 1, now()),('Paula', 'Johnson', 'paula@yahoo.com', '123456', 'Massachusetts', 'sales', 0, now()),('Tom', 'Spears', 'tom@yahoo.com', '123456', 'Massachusetts', 'sales', 0, now());


|method|TYPE|Queries|
|------|----|-------|
|show  |table|SHOW TABLES;|
|exit  |database|exit;|
|Select|Database|USE **use database**;|
|      |table   |SELECT * FROM **users**;<br>SELECT **first_name, last_name** FROM **users**;|
|      |table where|SELECT * FROM users WHERE location='Massachusetts';<br>SELECT * FROM **users** WHERE **location**=**'Massachusetts**' AND **dept**='**sales**';<br>SELECT * FROM **users** WHERE is_admin = **1**;<br>SELECT * FROM **users** WHERE is_admin > **0**;)
|      |table order|SELECT * FROM **users** ORDER BY **last_name** ASC;<br>SELECT * FROM **users** ORDER BY **last_name** DESC;|
|      |table like|SELECT * FROM **users** WHERE **dept** LIKE '**d%**';<br>SELECT * FROM **users** WHERE **dept** LIKE '**dev%**';<br>SELECT * FROM **users** WHERE **dept** LIKE '**%t**';<br>SELECT * FROM **users** WHERE **dept** LIKE '**%e%**';|
|Add New Column|table|ALTER TABLE **users** ADD **age VARCHAR(3)**;|
|Modify Column|table|ALTER TABLE **users** MODIFY COLUMN **age INT(3)**;|
|Update Row|table|UPDATE **users** SET **email** = '**freddy@gmail.com**' WHERE **id = 2**;|
|Select Distinct Rows|table|SELECT DISTINCT location FROM users;|
|Between (Select Range)|table|SELECT * FROM users WHERE age BETWEEN 20 AND 25;|
|group by|table|SELECT **age**, COUNT(**age**) FROM **users** GROUP BY **age**;<br>SELECT **age**, COUNT(**age**) FROM **users** WHERE **age > 20** GROUP BY **age**;<br>SELECT **age**, COUNT(**age**) FROM **users** GROUP BY **age** HAVING count(**age**) >=**2**;|

# CHAPTER-14_____________________________________________________In-Depth Python Features.

In [ ]:
# lambda, with statement,split, try/except, x for x in range(),

1. import **time**
1. import **random**
1. import **turtle**
1. import **os**
1. import **tkinter**
1. import **requests**
1. import **csv**

# CHAPTER-15_____________________________________________________Basic Statistics.

# CHAPTER-16_____________________________________________________Statistical graphs.

# CHAPTER-17_____________________________________________________Python Numpy.

## **Numpy** _is a Python library used for working with 1D,2D,3D array_
* **Array** _is same like the list used to store collection_
* **Array index** _is same as python index_

## CREATING numpy arrays 

<div class="alert alert-block alert-warning">                  
<center><h3><b>BASIC</b></h3></center>
</div>  

In [3]:
# 1d array
import numpy as np
arr_1d = np.array([1,2,3,4,5,6,7,8,9])
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 2d array
import numpy as np
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
# 3d array
import numpy as np
arr_3d = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
arr_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

<div class="alert alert-block alert-warning">                  
<center><h3><b>useing:-"arange"</b></h3></center>
</div>  

**arange:**  
it is used to make a np array by defining a range for it 
* it is used to make only 1-D array
* **Syntax:-**
* * np.arange(start,stop-1,step)

In [5]:
# arange(start,stop)
import numpy as np
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [7]:
# arange(start,stop,step)
import numpy as np
arr = np.arange(0,21,4)
arr

array([ 0,  4,  8, 12, 16, 20])

<div class="alert alert-block alert-warning">                  
<center><h3><b>useing:-"random"</b></h3></center>
</div>  

**random module**
|syntax|--USE--|
|------|-------|
|np.random.randint(start,stop,size)|it give the random array between the range of the size|
|np.random.random(size)|it give the random number between 0 to 1 of the given size|

In [14]:
# randint 1d
import numpy as np
arr=np.random.randint(5,19,4)
arr

array([14, 17, 10, 18])

In [15]:
# randint 2d
import numpy as np
arr=np.random.randint(5,19,(2,4))
arr

array([[13,  7, 11, 13],
       [12, 10, 15, 12]])

In [16]:
# randint 3d
import numpy as np
arr=np.random.randint(5,19,(2,4,6))
arr

array([[[17, 10, 15, 14, 13, 13],
        [ 7, 18,  9,  5, 13, 16],
        [ 7, 13,  9,  6, 18, 15],
        [ 9,  6, 17, 18,  6,  9]],

       [[16, 15, 14, 16,  8, 12],
        [ 9, 16,  8, 11, 15, 17],
        [18, 15, 13, 18, 11,  7],
        [ 6,  8,  9, 14,  8, 10]]])

***

In [17]:
# random 1d
import numpy as np
arr = np.random.random(4)
arr

array([0.81109525, 0.54825063, 0.14487131, 0.82824787])

In [18]:
# random 2d
import numpy as np
arr = np.random.random((2,4))
arr

array([[0.47740099, 0.14864884, 0.56872024, 0.27375748],
       [0.58237376, 0.90367401, 0.89409546, 0.61717411]])

In [19]:
# random 3d
import numpy as np
arr = np.random.random((2,4,6))
arr

array([[[0.07743122, 0.3776119 , 0.8698661 , 0.80444607, 0.47839819,
         0.56187775],
        [0.82326614, 0.90144645, 0.79535725, 0.76746851, 0.94289312,
         0.02940013],
        [0.65142055, 0.08986743, 0.32540603, 0.0723826 , 0.93595505,
         0.61366391],
        [0.18158003, 0.94205011, 0.42202287, 0.83051316, 0.84568007,
         0.36105203]],

       [[0.54619484, 0.69296648, 0.71950955, 0.99946001, 0.80920447,
         0.61804115],
        [0.03699399, 0.24268561, 0.63808847, 0.34505597, 0.67920782,
         0.51353867],
        [0.29096087, 0.25756638, 0.64428673, 0.8238065 , 0.25421889,
         0.57559579],
        [0.6373608 , 0.27201972, 0.24884959, 0.99618286, 0.18583868,
         0.98669255]]])

<div class="alert alert-block alert-warning">                  
<center><h3><b>-- OTHERS --</b></h3></center>
</div>  

|syntax|USE|
|------|---|
|np.zeros((3,4))|create a array of zeros of size 3\*4|
|np.ones((2,3,4),dtype=np.int16)|create a array of ones of size 2\*3\*4|
|np.full((2,2),7)|create a constant array of 7(in this case) of size 2\*2|
| np.eye(2)|create a 2\*2 identity matrix|
| np.empty((3,2))|create aempty matrix with garbage value ofsize 3\*2|

In [23]:
import numpy as np
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
import numpy as np
arr=np.ones((2,3,4),dtype=np.int16)
arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
import numpy as np
arr=np.full((2,2),7)
arr

array([[7, 7],
       [7, 7]])

In [2]:
import numpy as np
arr=np.eye(10)
arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
import numpy as np
arr=np.empty((3,2))
arr

array([[7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304]])

## Mathematics

<div class="alert alert-block alert-warning">                  
<center><h3><b>Arithmetic Operations</b></h3></center>
</div>  

|Syntax|USE|
|------|---|
|**\+**|Addition|
|**\-**|Subtraction|
|**\***|multiplaction|
|**\/**|division|
|np.sqrt(b)|Square root|
|np.sin(a)|Print sines of an array|
|np.cos(b)|Elementwise cosine|
|np,tan(b)|value of tan|
|np.log(a)|Elementwise natural logarithm|
|np.log2(a)|Elementwise natural logarithm with base 2|

In [30]:
a=np.arange(1,7)
b=np.arange(4,10)
print(a)
print(b)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [35]:
c=a+b
c

array([ 5,  7,  9, 11, 13, 15])

In [36]:
c=a-b
c

array([-3, -3, -3, -3, -3, -3])

In [37]:
c=a*b
c

array([ 4, 10, 18, 28, 40, 54])

In [38]:
c=a/b
c

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
       0.66666667])

In [39]:
c=np.sqrt(a)
c

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [40]:
c=np.sin(a)
c

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [41]:
c=np.cos(a)
c

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

In [42]:
c=np.tan(a)
c

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619])

In [43]:
c=np.log(a)
c

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [44]:
c=np.log2(a)
c

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 ])

<div class="alert alert-block alert-warning">                  
<center><h3><b>Aggregate Functions</b></h3></center>
</div>  

|syntax|USE|
|------|---|
|a.sum()|Array-wise sum
|a.min()|Array-wise minimum value
|b.max(axis=0)|Maximum value of an array row
|b.cumsum(axis=1)|Cumulative sum of the elements
|a.mean()|Mean
|np.median()|Median
|np.corrcoef()|Correlation coefficient
|np.std()|Standard deviation
|np.var()|variance|

In [51]:
a=np.random.randint(0,11,(2,5))
a

array([[4, 6, 3, 7, 3],
       [3, 6, 6, 0, 9]])

In [52]:
c=a.sum()
c

47

In [53]:
c=a.min()
c

0

In [58]:
#max value of all the rows
c=a.max(axis=0)
c

array([4, 6, 6, 7, 9])

In [62]:
# sum of numbers as we go up
c=a.cumsum(axis=1)
c

array([[ 4, 10, 13, 20, 23],
       [ 3,  9, 15, 15, 24]])

In [64]:
c=a.mean()
c

4.7

In [66]:
c=np.median(a)
c

5.0

In [69]:
c=np.corrcoef(a)
c

array([[ 1.       , -0.7000666],
       [-0.7000666,  1.       ]])

In [70]:
c=np.std(a)
c

2.4515301344262523

In [76]:
c=np.var(a)
c

6.01

## Array Manipulation

<div class="alert alert-block alert-warning">                  
<center><h3><b>Inspecting array</b></h3></center>
</div>

|syntax|USE|
|------|---|
|a.shape|tell the shaps of array|
|len(a)|tell length of the array|
|a.ndim|tell dimnation of the array|
|a.size|tell size of the array|
|a.dtype|tell datatypes of array elements|
|a.dtype.name|tell name of datatype of array elements| 
|a.astype(int)|convert data type of the aray element|

In [78]:
import numpy as np
a=np.random.randint(1,21,(3,5))
a

array([[ 4,  6, 20,  7, 20],
       [14, 17, 15, 15,  6],
       [ 7,  7, 20, 12,  9]])

In [80]:
c=a.shape
c

(3, 5)

In [81]:
c=len(a)
c

3

In [82]:
c=a.ndim
c

2

In [84]:
c=a.size
c

15

In [85]:
c=a.dtype
c

dtype('int32')

In [86]:
c=a.dtype.name
c

'int32'

In [87]:
c=a.astype(str)
c

array([['4', '6', '20', '7', '20'],
       ['14', '17', '15', '15', '6'],
       ['7', '7', '20', '12', '9']], dtype='<U11')

<div class="alert alert-block alert-warning">                  
<center><h3><b>Subsetting,Slicing, Indexing</b></h3></center>
</div> 

**slicing**

![array index](https://media.geeksforgeeks.org/wp-content/uploads/Numpy1.jpg)

***

In [88]:
a=np.arange(0,36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [90]:
a=a.reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

**index**  
<img src="https://www.oreilly.com/api/v2/epubs/9781449323592/files/httpatomoreillycomsourceoreillyimages2172112.png" style="width:300px">

In [92]:
print(a[0][1])
print(a[0][2])
print(a[0][3])
print(a[1][0])

1
2
3
6


**SUBSET**  
a[row,column,width]

In [94]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [96]:
sub=a[2:4]
sub

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [98]:
sub=a[2:4,1:6]
sub

array([[13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23]])

In [101]:
sub=a[2:5,2:5]
sub

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

<div class="alert alert-block alert-success">                  
<p><b>note:</b>if we change any value in subset it will cause change in his parent array also</p>
<p>to prevent that we can use <b>np.copy(a)</b></p>
</div>    

In [102]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [103]:
sub=a[2:5,2:5]
sub

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [105]:
sub[0][0]=1000
sub

array([[1000,   15,   16],
       [  20,   21,   22],
       [  26,   27,   28]])

In [106]:
a

array([[   0,    1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,   11],
       [  12,   13, 1000,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35]])

In [107]:
sub=np.copy(a[2:5,2:5])
sub

array([[1000,   15,   16],
       [  20,   21,   22],
       [  26,   27,   28]])

In [108]:
sub[0][0]=68783268
sub

array([[68783268,       15,       16],
       [      20,       21,       22],
       [      26,       27,       28]])

In [109]:
# no change
a

array([[   0,    1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,   11],
       [  12,   13, 1000,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35]])

<div class="alert alert-block alert-warning">                  
<center><h3><b>Adding / Removing elements</b></h3></center>
</div> 

|SYNTAX|USE|
|------|---|
|a.reshape((2,5))|Return a new array with shape(2,5)|
|np.append(a,temp)|Append items to an array|
|np.insert(a,1,5)|Insert items in an array|
|np.delete(a,[1])|Delete items from an array|

In [115]:
import numpy as np
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
b=a.reshape((2,5))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [117]:
temp=np.arange(10,16)
print("a =",a)
print("temp =",temp)
c=np.append(a,temp)
print("c =",c)

a = [0 1 2 3 4 5 6 7 8 9]
temp = [10 11 12 13 14 15]
c = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [119]:
c=np.insert(c,0,99)
c

array([99,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [120]:
c=np.delete(c,[0])
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

<div class="alert alert-block alert-warning">                  
<center><h3><b>Combining / splitting arrays</b></h3></center>
</div> 

In [131]:
a=np.array([[1,2,3,4,5],[11,22,33,44,55]])
b=np.array([[6,7,8,9,10],[66,77,88,99,110]])
print(a)
print(b)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
[[  6   7   8   9  10]
 [ 66  77  88  99 110]]


In [133]:
np.concatenate((a,b),axis=0)

array([[  1,   2,   3,   4,   5],
       [ 11,  22,  33,  44,  55],
       [  6,   7,   8,   9,  10],
       [ 66,  77,  88,  99, 110]])

In [134]:
np.concatenate((a,b),axis=1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110]])

In [140]:
c=np.vstack((a,b))
c

array([[  1,   2,   3,   4,   5],
       [ 11,  22,  33,  44,  55],
       [  6,   7,   8,   9,  10],
       [ 66,  77,  88,  99, 110]])

In [141]:
c2=np.hstack((a,b))
c2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110]])

In [148]:
np.hsplit(c2,5)

[array([[ 1,  2],
        [11, 22]]),
 array([[ 3,  4],
        [33, 44]]),
 array([[ 5,  6],
        [55, 66]]),
 array([[ 7,  8],
        [77, 88]]),
 array([[  9,  10],
        [ 99, 110]])]

In [150]:
np.vsplit(c,4)

[array([[1, 2, 3, 4, 5]]),
 array([[11, 22, 33, 44, 55]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[ 66,  77,  88,  99, 110]])]

In [154]:
for data in np.hsplit(c2,5):
    print(np.hsplit(data,2))

[array([[ 1],
       [11]]), array([[ 2],
       [22]])]
[array([[ 3],
       [33]]), array([[ 4],
       [44]])]
[array([[ 5],
       [55]]), array([[ 6],
       [66]])]
[array([[ 7],
       [77]]), array([[ 8],
       [88]])]
[array([[ 9],
       [99]]), array([[ 10],
       [110]])]


<div class="alert alert-block alert-warning">                  
<center><h3><b>OTHERS</b></h3></center>
</div> 

|SYNTAX|USE|
|------|---|
|a.reshape()|it reshape the array|
|np.transpose(a)| swip rows and columns with each other|
|np.linspace(0,2,9)|Create an array of evenly spaced values(number of samples)| 
|a.sort()|Sort an array|
|c.sort(axis=0)|Sort the elements of an array's axis|

In [167]:
import numpy as np
a=np.random.randint(1,45,15)
a

array([ 1, 40, 25, 16,  7, 15, 10, 11, 26, 25, 14, 22, 33, 42, 27])

In [168]:
a=a.reshape((3,5))
a

array([[ 1, 40, 25, 16,  7],
       [15, 10, 11, 26, 25],
       [14, 22, 33, 42, 27]])

In [169]:
a=np.transpose(a)
a

array([[ 1, 15, 14],
       [40, 10, 22],
       [25, 11, 33],
       [16, 26, 42],
       [ 7, 25, 27]])

In [170]:
np.sort(a,axis=0)

array([[ 1, 10, 14],
       [ 7, 11, 22],
       [16, 15, 27],
       [25, 25, 33],
       [40, 26, 42]])

In [174]:
np.linspace(0,4,9)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

# CHAPTER-18_____________________________________________________Python pandas.

## _Pandas is the most popular Python library for data analysis._

In [1]:
import pandas as pd

<div class="alert alert-block alert-warning">                  
<center><h3><b>Creating, Reading and Writing</b></h3></center>
</div>  

## Creating data
### types ->(DataFrame and the Series.)

**DataFrame**  
```A DataFrame is a table. It contains an array of individual entries, each of which has a certain value. Each entry corresponds to a row (or record) and a column.```

In [2]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

,Yes,No
0,50,131
1,21,2


In [3]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

,Bob,Sue
0,I liked it.,Pretty good.
1,It was awful.,Bland.


In [4]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

,Bob,Sue
Product A,I liked it.,Pretty good.
Product B,It was awful.,Bland.


**Series**  
```A Series, by contrast, is a sequence of data values. If a DataFrame is a table, a Series is a list. And in fact you can create one with nothing more than a list:```

In [5]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
''' A Series is, in essence, a single column of a DataFrame. So you can assign row labels to the Series 
the same way as before, using an index parameter. However, a Series does not have a column name, it 
only has one overall name '''
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

## Reading data files

In [7]:
'''if your data already have index as a first column use pd.read_csv("data.csv",index_col=0)'''
data = pd.read_csv("iris.csv")

In [8]:
data.shape

(150, 5)

In [9]:
data.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [10]:
data.tail()

,sepal_length,sepal_width,petal_length,petal_width,species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica


In [11]:
data.sample()

,sepal_length,sepal_width,petal_length,petal_width,species
95,5.7,3.0,4.2,1.2,versicolor


## Saving a file in CSV

In [12]:
data.to_csv("temp.csv")

<div class="alert alert-block alert-warning">                  
<center><h3><b>Indexing, Selecting & Assigning</b></h3></center>
</div>  

## Native accessors

In [13]:
data.species

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [14]:
data["species"]

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

## Indexing

```Index-based selection Pandas indexing works in one of two paradigms. The first is index-based selection: selecting data based on its numerical position in the data. iloc follows this paradigm.```

In [15]:
data.iloc[0]

sepal_length       5.1
sepal_width        3.5
petal_length       1.4
petal_width        0.2
species         setosa
Name: 0, dtype: object

In [16]:
"""iloc[row_start:row_end, column_start:column_end]"""
data.iloc[:,0]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [17]:
data.iloc[[2,50,77],-1]

2         setosa
50    versicolor
77    versicolor
Name: species, dtype: object

## Label-based selection
```The second paradigm for attribute selection is the one followed by the loc operator: label-based selection. In this paradigm, it's the data index value, not its position```

In [18]:
data.loc[0,"species"]

'setosa'

In [19]:
data.loc[:,["sepal_width","species"]]

,sepal_width,species
0,3.5,setosa
1,3.0,setosa
2,3.2,setosa
3,3.1,setosa
4,3.6,setosa
...,...,...
145,3.0,virginica
146,2.5,virginica
147,3.0,virginica
148,3.4,virginica


**iloc uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. So 0:10 will select entries 0,...,9. loc, meanwhile, indexes inclusively. So 0:10 will select entries 0,...,10**

## Manipulating the index

In [20]:
data.set_index("species")

,sepal_length,sepal_width,petal_length,petal_width
species,,,,
setosa,5.1,3.5,1.4,0.2
setosa,4.9,3.0,1.4,0.2
setosa,4.7,3.2,1.3,0.2
setosa,4.6,3.1,1.5,0.2
setosa,5.0,3.6,1.4,0.2
...,...,...,...,...
virginica,6.7,3.0,5.2,2.3
virginica,6.3,2.5,5.0,1.9
virginica,6.5,3.0,5.2,2.0


## Conditional selection

In [21]:
data.loc[data.sepal_length>=6.9]

,sepal_length,sepal_width,petal_length,petal_width,species
50,7.0,3.2,4.7,1.4,versicolor
52,6.9,3.1,4.9,1.5,versicolor
102,7.1,3.0,5.9,2.1,virginica
105,7.6,3.0,6.6,2.1,virginica
107,7.3,2.9,6.3,1.8,virginica
109,7.2,3.6,6.1,2.5,virginica
117,7.7,3.8,6.7,2.2,virginica
118,7.7,2.6,6.9,2.3,virginica
120,6.9,3.2,5.7,2.3,virginica
122,7.7,2.8,6.7,2.0,virginica


In [22]:
data.loc[data.species.isin(["setosa"])]

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
5,5.4,3.9,1.7,0.4,setosa
6,4.6,3.4,1.4,0.3,setosa
7,5.0,3.4,1.5,0.2,setosa
8,4.4,2.9,1.4,0.2,setosa
9,4.9,3.1,1.5,0.1,setosa


In [23]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [24]:
data.notnull().sum()

sepal_length    150
sepal_width     150
petal_length    150
petal_width     150
species         150
dtype: int64

<div class="alert alert-block alert-warning">                  
<center><h3><b>Summary Functions and Maps</b></h3></center>
</div>  

In [25]:
data.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [26]:
data.sepal_length.mean()

5.843333333333334

In [27]:
data.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [28]:
data.species.value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

## Maps

In [29]:
'''A map is a term, borrowed from mathematics, for a function that takes one set of values and "maps" them to another set of values.
In data science we often have a need for creating new representations from existing data, 
or for transforming data from the format it is in now to the format that we want it to be in later. 
Maps are what handle this work, making them extremely important for getting your work done


There are two mapping methods that you will use often'''

data.sepal_length.map(lambda x:x*2)

0      10.2
1       9.8
2       9.4
3       9.2
4      10.0
       ... 
145    13.4
146    12.6
147    13.0
148    12.4
149    11.8
Name: sepal_length, Length: 150, dtype: float64

In [30]:
data.sepal_length.map(lambda x:x*2)

0      10.2
1       9.8
2       9.4
3       9.2
4      10.0
       ... 
145    13.4
146    12.6
147    13.0
148    12.4
149    11.8
Name: sepal_length, Length: 150, dtype: float64

In [31]:
'''both map and apply works the same but apply can handle more complex task in column and row operational levels'''

def twice(row):
    return row.sepal_length*2

data.apply(twice, axis='columns')

0      10.2
1       9.8
2       9.4
3       9.2
4      10.0
       ... 
145    13.4
146    12.6
147    13.0
148    12.4
149    11.8
Length: 150, dtype: float64

<div class="alert alert-block alert-warning">                  
<center><h3><b>Grouping and Sorting</b></h3></center>
</div>  

In [36]:
"""groupby() is used gtob group the data according to the given peramater in pandas"""
data.groupby("species").species.count()

species
setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [39]:
'''You can think of each group we generate as being a slice of our DataFrame containing only data with values that match'''
data.groupby("species").mean()

,sepal_length,sepal_width,petal_length,petal_width
species,,,,
setosa,5.006,3.428,1.462,0.246
versicolor,5.936,2.770,4.260,1.326
virginica,6.588,2.974,5.552,2.026


In [45]:
df = pd.read_csv("titanic.csv")
display(df.head())

'''you can also group by more than one column'''
df.groupby(["class", "sex"]).apply(lambda df:df.loc[df.fare.idxmax()])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


C:\Users\updes\AppData\Local\Temp\ipykernel_14104\4255812431.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(["class", "sex"]).apply(lambda df:df.loc[df.fare.idxmax()])


survived  pclass     sex   age  sibsp  parch      fare  \
class  sex                                                              
First  female         1       1  female  35.0      0      0  512.3292   
       male           1       1    male  36.0      0      1  512.3292   
Second female         1       2  female  24.0      1      2   65.0000   
       male           0       2    male  21.0      0      0   73.5000   
Third  female         0       3  female   NaN      8      2   69.5500   
       male           0       3    male   NaN      8      2   69.5500   

              embarked   class    who  adult_male deck  embark_town alive  \
class  sex                                                                  
First  female        C   First  woman       False  NaN    Cherbourg   yes   
       male          C   First    man        True    B    Cherbourg   yes   
Second female        S  Second  woman       False  NaN  Southampton   yes   
       male          S  Second    man        True  NaN  Southampton    no   
Third  female        S   Third  woman       False  NaN  Southampton    no   
       male          S   Third    man        True  NaN  Southampton    no   

               alone  
class  sex            
First  female   True  
       male    False  
Second female  False  
       male     True  
Third  female  False  
       male    False

In [48]:
"""Another groupby() method worth mentioning is aggregate(),
which lets you run a bunch of different functions on your DataFrame simultaneously."""

data.groupby(["species"]).sepal_length.aggregate([len,"min", "max"])

,len,min,max
species,,,
setosa,50,4.3,5.8
versicolor,50,4.9,7.0
virginica,50,4.9,7.9


## Multi-indexes

In all of the examples we've seen thus far we've been working with DataFrame or Series objects with a single-label index. groupby() is slightly different in the fact that, depending on the operation we run, it will sometimes result in what is called a multi-index.

A multi-index differs from a regular index in that it has multiple levels. For example:

In [51]:
Mm = df.groupby(["class", "sex"]).fare.agg([len])
Mm

len
class  sex        
First  female   94
       male    122
Second female   76
       male    108
Third  female  144
       male    347

In [52]:
Mm.index

MultiIndex([( 'First', 'female'),
            ( 'First',   'male'),
            ('Second', 'female'),
            ('Second',   'male'),
            ( 'Third', 'female'),
            ( 'Third',   'male')],
           names=['class', 'sex'])

In [54]:
"""methods of multi-indices"""
Mm.reset_index()

,class,sex,len
0,First,female,94
1,First,male,122
2,Second,female,76
3,Second,male,108
4,Third,female,144
5,Third,male,347


## Sorting

In [55]:
Mm.reset_index().sort_values(by="len")

,class,sex,len
2,Second,female,76
0,First,female,94
3,Second,male,108
1,First,male,122
4,Third,female,144
5,Third,male,347


In [56]:
Mm.reset_index().sort_values(by="len", ascending=False)

,class,sex,len
5,Third,male,347
4,Third,female,144
1,First,male,122
3,Second,male,108
0,First,female,94
2,Second,female,76


<div class="alert alert-block alert-warning">                  
<center><h3><b>Data Types and Missing Values</b></h3></center>
</div>  

In [60]:
'''The data type for a column in a DataFrame or a Series is known as the dtype.'''
data.sepal_width.dtype

dtype('float64')

In [62]:
data.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

One peculiarity to keep in mind (and on display very clearly here) is that columns consisting entirely of strings do not get their own type; they are instead given the object type

In [63]:
data.sepal_width.astype("float32")

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float32

In [65]:
'''A DataFrame or Series index has its own dtype, too:'''
data.index.dtype

dtype('int64')

## Missing data

In [ ]:
"""Entries missing values are given the value NaN, short for "Not a Number". 
For technical reasons these NaN values are always of the float64 dtype.

Pandas provides some methods specific to missing data. To select NaN entries you can use pd.isnull() 
(or its companion pd.notnull())"""



In [67]:
df[df.deck.isnull()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False


In [68]:
df[pd.isnull(df.age)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True


In [76]:
df.deck.fillna("C")

0      C
1      C
2      C
3      C
4      C
      ..
886    C
887    B
888    C
889    C
890    C
Name: deck, Length: 891, dtype: object

In [79]:
df_temp = df.survived.replace(0,"dead")

In [80]:
df_temp

0      dead
1         1
2         1
3         1
4      dead
       ... 
886    dead
887       1
888    dead
889       1
890    dead
Name: survived, Length: 891, dtype: object

<div class="alert alert-block alert-warning">                  
<center><h3><b>Renaming and Combining</b></h3></center>
</div>  

In [82]:
df.rename(columns={"sex":"gender"})

,survived,pclass,gender,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [83]:
df.rename(index={0:"zero",1:"one"})

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
zero,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
one,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [85]:
df.rename_axis("id's of pessengers", axis="rows").rename_axis("features", axis="columns")

features,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
id's of pessengers,,,,,,,,,,,,,,,
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False


## Combining

In [86]:
to_be_concad_one = pd.read_csv("Position_Salaries.csv")
to_be_concad_two = pd.read_csv("Position_Salaries.csv")

print(to_be_concad_one.shape)
print(to_be_concad_two.shape)

(10, 3)
(10, 3)


In [87]:
pd.concat([to_be_concad_one,to_be_concad_two]).shape

(20, 3)

In [88]:
""".join()---------------------------.merge()"""

'.join()---------------------------.merge()'

In [92]:
to_be_concad_one.join(to_be_concad_two,lsuffix="_one",rsuffix="_two")

,Position_one,Level_one,Salary_one,Position_two,Level_two,Salary_two
0,Business Analyst,1,45000,Business Analyst,1,45000
1,Junior Consultant,2,50000,Junior Consultant,2,50000
2,Senior Consultant,3,60000,Senior Consultant,3,60000
3,Manager,4,80000,Manager,4,80000
4,Country Manager,5,110000,Country Manager,5,110000
5,Region Manager,6,150000,Region Manager,6,150000
6,Partner,7,200000,Partner,7,200000
7,Senior Partner,8,300000,Senior Partner,8,300000
8,C-level,9,500000,C-level,9,500000
9,CEO,10,1000000,CEO,10,1000000


# CHAPTER-19_____________________________________________________Statistical covariance.